object buenosAires {}
object catamarca {}
object chaco {}
object chubut {}
object cordoba {}
object corrientes {}
object entreRios {}
object formosa {}
object jujuy {}
object laPampa {}
object laRioja {}
object mendoza {}
object misiones {}
object neuquen {}
object rioNegro {}
object salta {}
object sanJuan {}
object sanLuis {}
object santaCruz {}
object santaFe {}
object santiagoDelEstero {}
object tierraDelFuego {}
object tucuman {}